export const POINTER_POSITION_PAD_SIZE = 100
export const POINTER_POSITION_GUIDE_GAP = 4

export const POINTER_POSITION_LAYER_X = 17
export const POINTER_POSITION_LAYER_Y = 23
export const POINTER_POSITION_LAYER_WIDTH = 66
export const POINTER_POSITION_LAYER_HEIGHT = 54

// Tune this value to change how far edge anchors sit inside the layer rectangle.
export const POINTER_POSITION_ANCHOR_INSET = 12

export const POINTER_POSITION_ANCHOR_LEFT = POINTER_POSITION_ANCHOR_INSET / POINTER_POSITION_LAYER_WIDTH
export const POINTER_POSITION_ANCHOR_CENTER_X = 0.5
export const POINTER_POSITION_ANCHOR_RIGHT =
  (POINTER_POSITION_LAYER_WIDTH - POINTER_POSITION_ANCHOR_INSET) / POINTER_POSITION_LAYER_WIDTH
export const POINTER_POSITION_ANCHOR_TOP = POINTER_POSITION_ANCHOR_INSET / POINTER_POSITION_LAYER_HEIGHT
export const POINTER_POSITION_ANCHOR_CENTER_Y = 0.5
export const POINTER_POSITION_ANCHOR_BOTTOM =
  (POINTER_POSITION_LAYER_HEIGHT - POINTER_POSITION_ANCHOR_INSET) / POINTER_POSITION_LAYER_HEIGHT

export const POINTER_POSITION_BOUNDS = {
  minX: -POINTER_POSITION_LAYER_X / POINTER_POSITION_LAYER_WIDTH,
  maxX:
    (POINTER_POSITION_PAD_SIZE - POINTER_POSITION_LAYER_X) /
    POINTER_POSITION_LAYER_WIDTH,
  minY: -POINTER_POSITION_LAYER_Y / POINTER_POSITION_LAYER_HEIGHT,
  maxY:
    (POINTER_POSITION_PAD_SIZE - POINTER_POSITION_LAYER_Y) /
    POINTER_POSITION_LAYER_HEIGHT
}
